CREATE TABLE robots(
    ip VARCHAR(20) NOT NULL,
    robotid INTEGER NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(robotid)
);

CREATE TABLE commands(
    command VARCHAR(2000) NOT NULL,
    colist VARCHAR(2000) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(command)
);

CREATE TABLE confuses(
    command VARCHAR(2000) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(command)
);

CREATE TABLE photos(
    photoname VARCHAR(200) NOT NULL,
    robotid INTEGER NOT NULL,
    uploadtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY(photoname)
);
